source 'https://cdn.cocoapods.org/'
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# Uncomment this line if you're using Swift
# use_frameworks!

target 'Sample' do
	pod 'Texture', :path => '../..'
end

